### ISSUE TITLE
Getting undefined Error 

### ISSUE THREAD

**Issue by gtmovvam** [ssddanbrown/gh-repo-stats#2]
While using this, i'm getting below error. If familiar with this let me know how to fix and use it.

gh-repo-stats % node index.js 
TypeError: Cannot read properties of undefined (reading 'x')
    at Object.fillMonthGaps (/private/tmp/gh-repo-stats/src/reports/util.js:59:40)
    at module.exports (/private/tmp/gh-repo-stats/src/reports/issues-opened-by-month.js:12:17)
    at runReportsOnData (/private/tmp/gh-repo-stats/src/generate-data.js:56:24)
    at generate (/private/tmp/gh-repo-stats/src/generate-data.js:38:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /private/tmp/gh-repo-stats/index.js:5:9

**Comment by ssddanbrown** [comment]
This could maybe occur when an empty array was passed into one of the functions used.
Have addressed in 066e36db5f38beef2dbbb0d3c7e81f30ec3bad8f
